export interface ProductMeasurements {
    chest: string;
    length: string;
    shoulder: string;
}

export interface Product {
    id: string;
    nameKey: string;
    descKey: string;
    imagePath: string;
    priceInRupees: number;
    size: string;
    brand: string;
    year: string;
    category: "tees" | "denim" | "knits" | "cargo";
    colorHex: string;
    hotness: 1 | 2 | 3 | 4 | 5;
    measurements: ProductMeasurements;
    conditionKey: "condExcellent" | "condVeryGood" | "condGood";
    materialKey: "matCotton" | "matDenim" | "matCorduroy" | "matWool" | "matFleece" | "matNylon";
}

export const CATEGORIES_META = {
    all: { labelKey: "browseCategories", href: "/catalog/all" },
    tees: { labelKey: "catTeesTitle", href: "/catalog/tees" },
    denim: { labelKey: "catDenimTitle", href: "/catalog/denim" },
    knits: { labelKey: "catKnitsTitle", href: "/catalog/knits" },
    cargo: { labelKey: "catCargoTitle", href: "/catalog/cargo" },
} as const;

export const PRODUCTS: Product[] = [
    {
        id: "prod-1",
        nameKey: "prod1Name",
        descKey: "prod1Desc",
        imagePath: "/products/vintage_tee.png",
        priceInRupees: 2900,
        size: "L",
        brand: "Champion (Classic)",
        year: "1994",
        category: "tees",
        colorHex: "#ff5722",
        hotness: 5,
        measurements: { chest: '22"', length: '29"', shoulder: '19.5"' },
        conditionKey: "condExcellent",
        materialKey: "matCotton",
    },
    {
        id: "prod-2",
        nameKey: "prod2Name",
        descKey: "prod2Desc",
        imagePath: "/products/denim_jeans.png",
        priceInRupees: 4800,
        size: "32 x 30",
        brand: "Levi's (Curated)",
        year: "1988",
        category: "denim",
        colorHex: "#2b4c7e",
        hotness: 4,
        measurements: { chest: 'N/A', length: '30" (inseam)', shoulder: 'N/A' },
        conditionKey: "condVeryGood",
        materialKey: "matDenim",
    },
    {
        id: "prod-3",
        nameKey: "prod3Name",
        descKey: "prod3Desc",
        imagePath: "/products/worker_shirt.png",
        priceInRupees: 3900,
        size: "M",
        brand: "Carhartt WIP",
        year: "1997",
        category: "knits",
        colorHex: "#bcaaa4",
        hotness: 4,
        measurements: { chest: '21"', length: '28"', shoulder: '18"' },
        conditionKey: "condVeryGood",
        materialKey: "matCorduroy",
    },
    {
        id: "prod-4",
        nameKey: "prod4Name",
        descKey: "prod4Desc",
        imagePath: "/products/cargo_pants.png",
        priceInRupees: 4400,
        size: "30 x 32",
        brand: "Rothco Vintage",
        year: "1992",
        category: "cargo",
        colorHex: "#4e5d44",
        hotness: 3,
        measurements: { chest: 'N/A', length: '32" (inseam)', shoulder: 'N/A' },
        conditionKey: "condGood",
        materialKey: "matCotton",
    },
    {
        id: "prod-5",
        nameKey: "prod5Name",
        descKey: "prod5Desc",
        imagePath: "/products/vintage_tee.png",
        priceInRupees: 3200,
        size: "XL",
        brand: "Nike Vintage",
        year: "1996",
        category: "tees",
        colorHex: "#009688",
        hotness: 4,
        measurements: { chest: '24"', length: '31"', shoulder: '21"' },
        conditionKey: "condExcellent",
        materialKey: "matCotton",
    },
    {
        id: "prod-6",
        nameKey: "prod6Name",
        descKey: "prod6Desc",
        imagePath: "/products/denim_jeans.png",
        priceInRupees: 5500,
        size: "L",
        brand: "Wrangler Heavyweight",
        year: "1985",
        category: "denim",
        colorHex: "#3f51b5",
        hotness: 5,
        measurements: { chest: '23"', length: '26" (jacket)', shoulder: '20"' },
        conditionKey: "condVeryGood",
        materialKey: "matDenim",
    },
    {
        id: "prod-7",
        nameKey: "prod7Name",
        descKey: "prod7Desc",
        imagePath: "/products/worker_shirt.png",
        priceInRupees: 4900,
        size: "L",
        brand: "Sears Vintage",
        year: "1974",
        category: "knits",
        colorHex: "#e91e63",
        hotness: 3,
        measurements: { chest: '22"', length: '27"', shoulder: '19"' },
        conditionKey: "condGood",
        materialKey: "matWool",
    },
    {
        id: "prod-8",
        nameKey: "prod8Name",
        descKey: "prod8Desc",
        imagePath: "/products/cargo_pants.png",
        priceInRupees: 6200,
        size: "M",
        brand: "Patagonia Synchilla",
        year: "1995",
        category: "cargo",
        colorHex: "#9c27b0",
        hotness: 5,
        measurements: { chest: '21.5"', length: '27.5"', shoulder: '18.5"' },
        conditionKey: "condExcellent",
        materialKey: "matFleece",
    },
    {
        id: "prod-9",
        nameKey: "prod9Name",
        descKey: "prod9Desc",
        imagePath: "/products/vintage_tee.png",
        priceInRupees: 3800,
        size: "M",
        brand: "Nirvana Tour Tee",
        year: "1993",
        category: "tees",
        colorHex: "#212121",
        hotness: 5,
        measurements: { chest: '20"', length: '28"', shoulder: '18"' },
        conditionKey: "condVeryGood",
        materialKey: "matCotton",
    },
    {
        id: "prod-10",
        nameKey: "prod10Name",
        descKey: "prod10Desc",
        imagePath: "/products/denim_jeans.png",
        priceInRupees: 4200,
        size: "30 x 32",
        brand: "Lee Riders",
        year: "1991",
        category: "denim",
        colorHex: "#795548",
        hotness: 3,
        measurements: { chest: 'N/A', length: '32" (inseam)', shoulder: 'N/A' },
        conditionKey: "condGood",
        materialKey: "matDenim",
    },
    {
        id: "prod-11",
        nameKey: "prod11Name",
        descKey: "prod11Desc",
        imagePath: "/products/worker_shirt.png",
        priceInRupees: 5200,
        size: "XL",
        brand: "Polo Ralph Lauren",
        year: "1992",
        category: "knits",
        colorHex: "#607d8b",
        hotness: 4,
        measurements: { chest: '25"', length: '30"', shoulder: '22"' },
        conditionKey: "condExcellent",
        materialKey: "matWool",
    },
    {
        id: "prod-12",
        nameKey: "prod12Name",
        descKey: "prod12Desc",
        imagePath: "/products/cargo_pants.png",
        priceInRupees: 3700,
        size: "L",
        brand: "Columbia Sportswear",
        year: "1990",
        category: "cargo",
        colorHex: "#00bcd4",
        hotness: 4,
        measurements: { chest: '23"', length: '28"', shoulder: '20"' },
        conditionKey: "condVeryGood",
        materialKey: "matNylon",
    },
];
